Updated README.md and created 2024-09-16-SeizurePrediction-LLM-VIT.md…
pcdslab/PCDSLab.github.io pull request #25
Opened 2024-09-16 19:59 UTC by Paras1242

… file

Updated README.md with steps to install github desktop, and created a file for SeizurePrediction with LLM and VIT in software\_posts

2024-09-17 12:19 UTC, Prof-S requested changes

2024-09-18 15:02 UTC, Paras1242 commented
I have made the requested changes and created a pull request.

2024-09-19 10:43 UTC, Prof-S approved these changes

2024-09-19 10:43 UTC, Prof-S commented on README.md
> +1. Open your your local copy of the repository `https://github.com/pcdslab/PCDSLab.github.io` from GitHub Desktop
Has a typo

2024-09-19 10:43 UTC, Prof-S commented on README.md
> +1. Open your your local copy of the repository `https://github.com/pcdslab/PCDSLab.github.io` from GitHub Desktop
has a typo

2024-09-19 10:43 UTC, merged